version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: uniroom_db_v3
    restart: always
    ports:
      - "5435:5432"  # <--- IMPORTANTE: Mapeo del puerto 5435 externo
    environment:
      POSTGRES_USER: uniroom_user
      POSTGRES_PASSWORD: '12345'
      POSTGRES_DB: uniroom
    volumes:
      - ./postgres-data:/var/lib/postgresql/data_db