services:
  db:
    image: postgres:15-alpine
    container_name: uniroom_db_v3
    restart: always
    ports:
      - "5435:5432"  # <--- IMPORTANTE: Mapeo del puerto 5435 externo
    environment:
      POSTGRES_USER: uniroom_user
      POSTGRES_PASSWORD: '12345'
      POSTGRES_DB: uniroom
    volumes:
      - uniroom_data:/var/lib/postgresql/data
      - .:/app
      - ./uploads:/app/uploads
volumes:
  uniroom_data:
